##
##

class HCLComponents(object):
    PKVAR_CB_VERSION = 'cb_version = "{{ CB_VERSION }}"'
    PKVAR_LINUX_TYPE = 'os_linux_type = "{{ LINUX_TYPE }}"'
    PKVAR_LINUX_RELEASE = 'os_linux_release = "{{ LINUX_RELEASE }}"'
    PKVAR_OS_IMAGE_NAME = 'os_image_name = "{{ OS_IMAGE_NAME }}"'
    PKVAR_OS_IMAGE_OWNER = 'os_image_owner = "{{ OS_IMAGE_OWNER }}"'
    PKVAR_OS_IMAGE_USER = 'os_image_user = "{{ OS_IMAGE_USER }}"'
    PKVAR_AWS_REGION = 'region_name = "{{ AWS_REGION }}"'
    PKVAR_HOST_PREP_REPO = 'host_prep_repo = "{{ HOST_PREP_REPO }}"'

    PKVAR_AZURE_RG = ''
    PKVAR_IMAGE_PUBLISHER = ''
    PKVAR_IMAGE_OFFER = ''
    PKVAR_IMAGE_SKU = ''
    PKVAR_LOCATION = ''

    PKVAR_GCP_ACCOUNT = ''
    PKVAR_IMAGE_FAMILY = ''
    PKVAR_GCP_PROJECT = ''
    PKVAR_GCP_ZONE = ''

    PKVAR_VSPHERE_HOSTNAME = 'vsphere_hostname = "{{ VMWARE_HOSTNAME }}"'
    PKVAR_VSPHERE_USERNAME = 'vsphere_username = "{{ VMWARE_USERNAME }}"'
    PKVAR_VSPHERE_PASSWORD = 'vsphere_password = "{{ VMWARE_PASSWORD }}"'
    PKVAR_VSPHERE_DATACENTER = 'vsphere_datacenter = "{{ VMWARE_DATACENTER }}"'
    PKVAR_VSPHERE_CLUSTER = 'vsphere_cluster = "{{ VMWARE_CLUSTER }}"'
    PKVAR_VSPHERE_DATASTORE = 'vsphere_datastore = "{{ VMWARE_DATASTORE }}"'
    PKVAR_VSPHERE_FOLDER = 'vsphere_folder = "{{ VMWARE_FOLDER }}"'
    PKVAR_VM_GUEST_OS_TYPE = 'vm_guest_os_type = "{{ VMWARE_OS_TYPE }}"'
    PKVAR_VM_CPU_CORES = 'vm_cpu_cores = "{{ VMWARE_CPU_CORES }}"'
    PKVAR_VM_MEM_SIZE = 'vm_mem_size = "{{ VMWARE_MEM_SIZE }}"'
    PKVAR_VM_DISK_SIZE = 'vm_disk_size = "{{ VMWARE_DISK_SIZE }}"'
    PKVAR_VSPHERE_NETWORK = 'vsphere_network = "{{ VMWARE_NETWORK }}"'
    PKVAR_OS_ISO_CHECKSUM = 'os_iso_checksum = "{{ OS_ISO_CHECKSUM }}"'
    PKVAR_OS_SW_URL = 'os_sw_url = "{{ OS_SW_URL }}"'
    PKVAR_BUILD_PASSWORD = 'build_password = "{{ VMWARE_BUILD_PASSWORD }}"'
    PKVAR_BUILD_PASSWORD_ENCRYPTED = 'build_password_encrypted = "{{ VMWARE_BUILD_PWD_ENCRYPTED }}"'
    PKVAR_VM_GUEST_OS_LANGUAGE = 'vm_guest_os_language = "en_US"'
    PKVAR_VM_GUEST_OS_KEYBOARD = 'vm_guest_os_keyboard = "us"'
    PKVAR_OS_TIMEZONE = 'os_timezone = "{{ OS_TIMEZONE }}"'
    PKVAR_SSH_PUBLIC_KEY = 'ssh_public_key = "{{ SSH_PUBLIC_KEY }}"'
